#!/bin/bash

{ cat hooks/images.csv; echo; } | grep '\S' | {
    read header
    while IFS=";" read -r dockerfile args tag; do
        if [ -z "$tag" ]; then
            tag=$(cut -d "/" -f1 <<< $dockerfile)
        fi
        docker push $DOCKER_REPO:$tag
    done
}
